### ISSUE TITLE
ndnperf client only supports TCP faces to forwarder

### ISSUE THREAD

**Issue by eric135** [Kanemochi/NDN_Benchmark_Test#4]
It seems that the ndnperf client connects to the forwarder only over TCP, while ndnperfserver is able to connect over a Unix stream socket. Unix stream sockets are the preferred method for connecting local applications, so I was curious why TCP was chosen for the client and whether it would be better to allow the use of Unix stream sockets by the client as well.

**Comment by Nayald** [comment]
I choose to use TCP for the client so that it is not mandatory for the client computer to run a NFD instance. This way, the client can connect to any instance as needed. For the server, it is a Unix socket because it was easier to register a prefix than with a TCP socket some years ago (+ the logic of local cache). Before I revamp my C++ client, it was also a Unix socket but I was not satisfied to run 2+ NFD instances for my benchmarks when they were on two different computers. I can add it back if you want (+ ip/port as parameters instead of hardcoded values).
